### PR TITLE
Inject AUTHOR flags and assure PERL_USE_UNSAFE_INC=0 during testing

### PR DESCRIPTION
**Pull request by toddr**

### CODE REVIEW

**Comment by chocolateboy** [comment]
Thanks. What's the reason for each setting?

**Comment by toddr** [comment]
PERL_USE_UNSAFE_INC=0 assures that newer perls will install the module correctly without a dependance on . in `@`INC

The other flags assure that any unit tests flagged for AUTHOR only still get run on travis.

**Comment by chocolateboy** [comment]
`PERL_USE_UNSAFE_INC=0` seems OK. Happy to consider the other three if and when there's a concrete use case for them. Please raise a separate PR for those if/when the time comes.

**Comment by toddr** [comment]
It's just a safety to make sure now and future travis smoker runs don't miss stuff. If you're not interested, feel free to reject it and we can re-visit when something is missed :)

**Comment by toddr** [comment]
This is all moot until it's enabled in travis.

**Pull request closed without merging**
